"""Add order and order_item tables

Revision ID: e34f61ace542
Revises: 9b1b34c0e35d
Create Date: 2025-06-06 12:14:56.990125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34f61ace542'
down_revision = '9b1b34c0e35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('total_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('display_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_goods_disposal_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gifting_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_income_estimate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('actual_unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_gifting_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
